version: "3"

services:

  db:
    image: "postgres:12.5"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: always
    ports:
      - 5432:5432

  app:
    build: .
    command: "poetry run uvicorn src.main:app --host 0.0.0.0 --port 9050 --reload"
    volumes:
      - "./src:/app/src"
    ports:
      - 9050:9050
    depends_on:
      - db
    env_file:
      - ".env"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/abyssinian"
    entrypoint: ["/app/entrypoint.sh"]