version: "3.5"

services:

  db:
    image: "postgres:12.5"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: always
    ports:
      - "8001:8001"
    command: -p 8001

  app:
    build:
      context: .
      target: run
    command: "poetry run uvicorn src.main:app --host 0.0.0.0 --port 9050 --reload"
    volumes:
      - "./src:/app/src"
    ports:
      - "9050:9050"
    depends_on:
      - db
    env_file:
      - ".env"
    environment:
      RDS_HOSTNAME: "db"
    entrypoint: ["/app/entrypoint.sh"]

  test:
    build:
      context: .
      target: test
    volumes:
      - "./src:/app/src"
      - "./tests:/app/tests"
    command: "sleep infinity"
    env_file:
      - ".env.test"
