"""Init db

Revision ID: b2b88e7e8e65
Revises: 
Create Date: 2022-07-07 15:24:04.417259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
import models

revision = 'b2b88e7e8e65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_codes',
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_coach_session_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_communication_request_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_care_navigation_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_case_manager_notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_additional_session_request_enabled', sa.Boolean(), nullable=True),
    sa.Column('coach_session_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('coaches',
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('sessions_limit_per_week', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', models.base.GUID(), nullable=False),
    sa.Column('access_code_id', models.base.GUID(), nullable=True),
    sa.Column('coach_id', models.base.GUID(), nullable=True),
    sa.Column('is_agree_emails', sa.Boolean(), nullable=True),
    sa.Column('is_agree_terms_conditions', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    op.drop_table('coaches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('access_codes')
    # ### end Alembic commands ###
